

# Credenciales de Supabase
supabase_url = "https://daphkqhhmbleywzfrkuf.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhcGhrcWhobWJsZXl3emZya3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTI0MDUsImV4cCI6MjA3Mzg2ODQwNX0.3JvQ6FUxwl15ILcO3wzduwhWCp9eDaf7u57ph3lDF_w"